name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".rusty-hook.toml"
      - "**/Makefile.toml"
      - "README.md"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Update submodule
        run: |
          git submodule update --remote
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2
      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "v0.17.5"

      - name: Pre Build
        run: |
          npm i
          cargo check
      - name: Build
        run: trunk build --release
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
