name: Create Sitemap
on:
  workflow_dispatch:
  schedule:
    #? every sunday at 00:00
    - cron: "0 0 * * 0"
  repository_dispatch:
    types: [modified_pages]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'payload: ${{ toJSON(github.event.client_payload) }}'"

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: clone repos
        run: |
          ls -1
          git clone https://github.com/RustLangES/blog.git
          git clone https://github.com/RustLangES/RustLangES.github.io.git home
          git clone https://github.com/RustLangES/rust-book-es.git book
          git clone https://github.com/RustLangES/rust-para-dotnet-devs.git dotnet

      - name: generate sitemap.xml
        run: |
          chmod +x generate.sh
          ./generate.sh
          # git diff generated/dates_and_paths.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update the sitemap"
          add: "generated/dates_and_paths.txt"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Sitemap"
          files: |
            sitemap.xml

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: RustLangES/RustLangES.github.io
          event-type: deploy
