# * usage: act.exe -j test -s GITHUB_TOKEN="$(gh auth token)"
name: test
on:
  repository_dispatch:
    types: [test]

permissions:
  contents: write
  # pages: write #? to deploy to Pages
  # id-token: write #? to verify the deployment originates from an appropriate source

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # todo: cache unix deps https://github.com/actions/cache
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: clone repos
        run: |
          ls -1
          git clone https://github.com/RustLangES/blog.git
          git clone https://github.com/RustLangES/RustLangES.github.io.git home
          git clone https://github.com/RustLangES/rust-book-es.git book

      - name: generate sitemap.xml
        run: |
          chmod +x generate.sh
          ./generate.sh
          ls -1

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "canary"
          prerelease: true
          title: "Development Build"
          files: |
            sitemap.xml
