# * usage: act.exe -j test -s GITHUB_TOKEN="$(gh auth token)"
name: test
on:
  repository_dispatch:
    types: [test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hi 🎈
        run: |
          ls -1
          echo "One or more files in the docs folder has changed."

      # todo: cache unix deps https://github.com/actions/cache
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: ls
        run: |
          ls -1
          git clone https://github.com/RustLangES/blog.git
          git clone https://github.com/RustLangES/RustLangES.github.io.git home
          git clone https://github.com/RustLangES/rust-book-es.git book

      - name: ls
        run: |
          chmod +x gen-articles.sh
          ./gen-articles.sh > gen-articles.txt
          chmod +x gen-weekly.sh
          ./gen-weekly.sh > gen-weekly.txt
          chmod +x gen-home.sh
          ./gen-home.sh > gen-home.txt
          chmod +x gen-book.sh
          ./gen-book.sh > gen-book.txt
          cargo run --bin tags > gen-tags.txt
          cat gen-articles.txt gen-weekly.txt gen-book.txt gen-home.txt gen-tags.txt > dates_and_paths.txt
          # cat dates_and_paths.txt
          cargo run --bin generate
          ls -1

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "canary"
          prerelease: true
          title: "Development Build"
          files: |
            sitemap.xml
