# * usage: act.exe -j test -s GITHUB_TOKEN="$(gh auth token)"
name: test sitemap generation
on:
  repository_dispatch:
    types: [test]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'payload: ${{ toJSON(github.event.client_payload) }}'"
      # todo: cache unix deps❓ https://github.com/actions/cache
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: clone repos
        run: |
          ls -1
          git clone https://github.com/RustLangES/blog.git
          git clone https://github.com/RustLangES/RustLangES.github.io.git home
          git clone https://github.com/RustLangES/rust-book-es.git book
          git clone https://github.com/RustLangES/rust-para-dotnet-devs.git dotnet

      - name: generate sitemap.xml
        run: |
          chmod +x generate.sh
          ./generate.sh
          git diff generated/dates_and_paths.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: "[${{ toJSON(github.event.client_payload.from) }}] update."
          add: "generated/dates_and_paths.txt"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "canary"
          prerelease: true
          title: "Preview"
          files: |
            sitemap.xml

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ph4un00b/RustLangES.github.io
          event-type: sitemap_changed
